project:
  type: book
  output-dir: docs

book:
  title: "Markov Switching Leisure & Enterteinment and VIX Markov-Switching investing"
  author:
    - name: "Oscar Valdemar De la Torre Torres"
      affiliation: "Universidad Michoacana de San Nicol√°s de hidalgo"
      orcid: "0000-0002-1234-5678"
      email: "oscar.delatorre.torres@umich.mx"
  date: "07/10/2025"
  chapters:
    - index.qmd
    - part: "Data Gathering and processing"
      chapters:
        - datagathering.qmd
        - backtests.qmd
    - part: "References"
      chapters:
        - references.qmd
  page-footer: "Copyright 2025: Oscar Valdemar De la Torre Torres. All rights reserved."

bibliography: biblio.bib
csl: cya.csl
toc_depth: 4

format:
  html:
    theme: united
#  pdf:
 #    documentclass: scrreprt

title-block-banner: true
title-block-banner-color: "orange"

editor: source
lang: en-En
